# Generated by Django 5.0.2 on 2024-02-23 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Category title')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('logo_url', models.URLField(verbose_name='Logo URL')),
                ('description', models.TextField()),
                ('order', models.IntegerField(unique=True, verbose_name='Category order')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Chapter title')),
                ('order', models.IntegerField(verbose_name='Chapter order')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='drfapi.category')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('topic', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Task title')),
                ('description', models.TextField(verbose_name='Task description')),
                ('starter_css_code', models.TextField(blank=True, null=True, verbose_name='Starter CSS code')),
                ('target', models.TextField(verbose_name='HTML Target')),
                ('order', models.IntegerField(verbose_name='Task order')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='drfapi.chapter')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('chapter', 'order')},
            },
        ),
    ]
