# Generated by Django 4.2.7 on 2024-02-25 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Category title')),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True)),
                ('logo_url', models.URLField(verbose_name='Logo URL')),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(unique=True, verbose_name='Category order')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Task title')),
                ('description', models.TextField(verbose_name='Task description')),
                ('completed', models.BooleanField(default=False)),
                ('starter_css_code', models.TextField(blank=True, null=True, verbose_name='Starter CSS code')),
                ('target', models.TextField(verbose_name='HTML Target')),
                ('order', models.PositiveIntegerField(verbose_name='Task order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='drfapi.category')),
            ],
            options={
                'ordering': ['category', 'order'],
                'unique_together': {('category', 'order')},
            },
        ),
    ]
