# Generated by Django 5.0.2 on 2024-02-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='topic',
            new_name='category',
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('category', 'order')},
        ),
    ]
