# Generated by Django 4.2.7 on 2024-02-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfapi', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(unique=True, verbose_name='Category order'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Chapter order'),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Task order'),
        ),
    ]
