# Generated by Django 4.2.7 on 2024-02-24 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfapi', '0005_alter_category_order_alter_chapter_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['category', 'order']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['chapter', 'order']},
        ),
    ]
